# Converted from /ctm/block17a.properties and /ctm/DOOMrandomterrain.png
# Individual tiles are in /ctm/randomterrain
#Mon Mar 25 11:55:25 EDT 2013
faces=bottom top
tiles=255
metadata=2
method=random
