# Converted from /ctm/block17b.properties and /ctm/doomctm.png
# Individual tiles are in /ctm/doomctm
#Mon Mar 25 11:55:26 EDT 2013
matchTiles=jungle_log_top
faces=bottom top
tiles=64-75 80-91 96-107 112-123
metadata=3
method=ctm
